syntax on
set showmode
set showcmd
set mouse=a
set encoding=utf-8
set t_Co=256
set autoindent
set shiftwidth=4
set expandtab
set softtabstop=4
set number
set nowrap
set scrolloff=5
set sidescrolloff=15
set showmatch
set hlsearch
set incsearch
set ignorecase
set autochdir
set autoread
set listchars=tab:»■,trail:■
set list
set wildmenu
set wildmode=longest:list,full
set wrap
set linebreak
set wrapmargin=2
